SET SERVEROUTPUT ON;

--PRUEBAS SALTO BUNGEE
DELETE FROM GUSANO WHERE idEquipo = 1
DELETE FROM EQUIPO WHERE idEquipo = 1

INSERT INTO EQUIPO
(Nombre, letra, derrotas, victorias, idPartida)
VALUES
('UNO','W',0,0,1);

SELECT * FROM EQUIPO;

INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES(100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES(100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES(100,1,NULL);

SELECT * FROM GUSANO;

EXEC CARGAR_TABLERO(1);
EXEC VER_TABLERO(1);

EXEC SALTO_BUNGEE(1 , 16, 12, 1)

--PRUEBAS CONTROL 8 GUSANOS POR EQUIPO


--PRUEBAS Trigger gusanoSoloEnAire

INSERT INTO  TABLERO (id,X_columnas,Y_filas) VALUES (1,50,15);
EXEC CARGAR_TABLERO(1);

UPDATE CELDA
   SET Contenido = 'W'
 WHERE TableroId = idTablero
   AND X_Columna =  0
   AND Y_Fila = 13;
