SET SERVEROUTPUT ON;

--PRUEBAS SALTO BUNGEE
DELETE FROM GUSANO WHERE idEquipo = 1
DELETE FROM EQUIPO WHERE idEquipo = 1

INSERT INTO EQUIPO
(Nombre, letra, derrotas, victorias, idPartida)
VALUES
('UNO','W',0,0,1);

SELECT * FROM EQUIPO;

INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES (100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES(100,1,NULL);
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES(100,1,NULL); 
INSERT INTO GUSANO (salud, idEquipo, accion) VALUES(100,1,NULL);

SELECT * FROM GUSANO;

EXEC CARGAR_TABLERO(1);
EXEC VER_TABLERO(1);

EXEC SALTO_BUNGEE(1 , 16, 12, 1)

--PRUEBAS CONTROL 8 GUSANOS POR EQUIPO
