SET SERVEROUTPUT ON;

INSERT INTO EQUIPO
(Nombre, letra, derrotas, victorias)
VALUES
('UNO','W',0,0);

SELECT * FROM EQUIPO;

INSERT INTO GUSANO
(salud, idEquipo, accion)
VALUES
(100,1,NULL);

SELECT * FROM GUSANO;

EXEC CARGAR_TABLERO(1);
EXEC VER_TABLERO(1);

EXEC SALTO_BUNGEE(1 , 16, 12, 1)